export const enum Paths {
  Auth = "auth",
  Example = "example",
  Feed = "feed",
  FullScreenPlayer = "fullScreenPlayer",
  Login = "login",
  Main = "main",
  MovieDetail = "movieDetail",
  Profile = "profile",
  Register = "register",
  Search = "search",
  SelectCountry = "selectCountry",
  Startup = "startup",
  Video = "video",
}
